#!/bin/bash

TMP="$(mktemp -d /tmp/pcfutbol-player-XXXXXXX)"
INPUT_FILE="$1"

# Based on https://gitlab.com/spisemisu/pcx-utils/-/blob/master/fut-img-players.sh#L31-47
convert "$INPUT_FILE" -alpha remove "BMP2:$TMP/0.bmp"
convert "$TMP/0.bmp" -resize 32x32 "BMP2:$TMP/1.bmp"
convert "$TMP/1.bmp" -shave 1x1 -bordercolor Black -border 1x1 -type palette -compress none -remap palette.bmp "BMP2:$TMP/2.bmp"

bin/pcx-colourpalette "bmp=$TMP/2.bmp"

rm -r "$TMP"
